#create pipeline with some name
name: shahin app containerization pipeline
# trigger-- when this pipeline should start
on:
  push:
    branches:
      - "dev"

jobs:
  shahin-sast-job:
    runs-on: self-hosted
    steps:
      - name: checking docker version and sonar scanner
        run: |
          sonar-scanner --version
          pwd
      - name: using pre-defined github workflow to copy gitrepo to runners machine
        uses: actions/checkout@v4
      
      - name: using local sonar-scanner
        run: |
          sonar-scanner.bat -D"sonar.projectKey=shahin-python-project" -D"sonar.sources=." -D"sonar.host.url=${{ secrets.SONAR_HOST_URL }}" -D"sonar.token=${{ secrets.SONAR_TOKEN }}"      

      - name: uploading artifact
        uses: actions/upload-artifact@v4
        with:
          name: shahin-artifact
          path: |
            .
            !**/.git*
            !**/*.md
            !**/.scannerwork
          
  shahin-build-job:
    runs-on: ubuntu-latest
    needs: shahin-sast-job
    steps:
      - name: checking general message
        run: |
          echo "checking docker things"
          docker version
          docker-compose version
      
      - name: downloading artifact 
        uses: actions/download-artifact@v4
        with: 
          name: shahin-artifact  
          path: .

      - name: docker compose and build 
        run: |
          ls -a
          docker-compose up -d
          sleep 2
          docker-compose ps 
    
      - name: verify health check page by accessing it
        run: | 
          echo "access health html page using curl" 
          curl -f http://localhost:1234/health.html  

      - name: ecr-publish
        uses: bitovi/github-actions-ecr-publish@v0.1.0
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_default_region: us-east-1
          aws_ecr_repo_name: bmo-webui-app
          image_tag: shahingitactionsv1    