#create pipeline with some name
name: shahin app containerization pipeline
# trigger-- when this pipeline should start
on:
  push:
    branches:
      - "dev"
#jobs we want to perform
jobs:
  shahin-image-build:
    runs-on: ubuntu-latest
    # this is the runner which provisioned by github backend for this job
    steps:
      - name: run some basic commands on above server to do some verification
        run: |
          uname -r 
          whoami
          cat /etc/os-release
          docker version
          docker-compose version
          sonar-scanner --version
      - name: using pre-defined github workflow to copy gitrepo to runners machien
        uses: actions/checkout@v4



      - name: verify github code and use docker compose to build and create
        run: |
          ls -a
          docker-compose up -d
          sleep 2
          docker-compose ps 
    
      - name: verify health check page by accessing it
        run: | 
          echo "access health html page using curl" 
          curl -f http://localhost:1234/health.html
    
      - name: try to login using docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      # - name: setup docker buildx
      #   uses: docker/setup-buildx-action@v3  

      - name: rebuild image in docker hub format and push it to docker hub
        uses: docker/build-push-action@v5 
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/shahinapp:v2

      - name: docker logout
        run: docker logout